modLoader="javafml"
loaderVersion="[35,)"
license="ISC License"
[[mods]]
modId="paintblocks"
version="1.2.0"
displayName="Paint Blocks"
logoFile="paintblocks.png"
credits="Credit to TurtyWurty and TelepathicGrunt for the tutorials"
authors="Justin Pridgen (BokuWaBoingo)"
description="Paint Blocks for your builds. (Based on CSS Keywords)"
